version: '3.4'
services:
  develop:
    image: volkherscholz/tensorflow-gdcm
    volumes:
      - ..:/workspace:cached
      - ../../dicomml-experimentation:/workspace/notebooks
    command: /bin/sh -c "while sleep 1000; do :; done"