version: '3.4'
services:
  develop:
    image: eu.gcr.io/belimo-ifa-dev/tensorflow-base:0.1.0
    volumes:
      - ..:/workspace:cached
      - ../../dicomml-experimentation:/workspace/notebooks
    command: /bin/sh -c "while sleep 1000; do :; done"%